name: VMware Compliance Audit

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ansible Compliance Audit Playbook
        env:
          VMWARE_HOST: "vcenter.mhy.com"
          VMWARE_USER: "administrator@vsphere.local"
          VMWARE_PASSWORD: "Admin@1234"
          VMWARE_VALIDATE_CERTS: "no"
        run: |
          source ~/ans-labs/ans-env/bin/activate
          ansible-playbook check_vcenter.yml \
            -e "vcenter_hostname=vcenter.mhy.com" \
            -e "vcenter_admin_user=administrator@vsphere.local" \
            -e "vcenter_admin_pass=Admin@1234" \
            -e "hostname=vcenter.mhy.com" \
            -e "username=administrator@vsphere.local" \
            -e "password=Admin@1234" \
            -e "validate_certs=false"