name: VMware Compliance Audit

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ansible Compliance Audit Playbook
        env:
          # متغيرات البيئة العامة التي يقرأها موديل VMware تلقائياً
          VMWARE_HOST: ${{ secrets.VCENTER_HOSTNAME }}
          VMWARE_USER: ${{ secrets.VCENTER_USERNAME }}
          VMWARE_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
          VMWARE_VALIDATE_CERTS: "no"
          # المتغيرات المخصصة باسم ملفك
          VCENTER_HOST: ${{ secrets.VCENTER_HOSTNAME }}
          VCENTER_USER: ${{ secrets.VCENTER_USERNAME }}
          VCENTER_PASS: ${{ secrets.VCENTER_PASSWORD }}
        run: |
          source ~/ans-labs/ans-env/bin/activate
          ansible-playbook check_vcenter.yml \
            -e "vcenter_hostname=$VCENTER_HOST" \
            -e "vcenter_admin_user=$VCENTER_USER" \
            -e "vcenter_admin_pass=$VCENTER_PASS" \
            -e "hostname=$VCENTER_HOST" \
            -e "username=$VCENTER_USER" \
            -e "password=$VCENTER_PASS" \
            -e "validate_certs=false"